name: Build

on: [push]

jobs:
  backend:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Downgrade Composer
      run: |
        echo "Temporary, see https://github.com/octobercms/october/issues/5033"
        sudo composer self-update 1.10.17
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install
    - name: PHPUnit
      run: |
        cd plugins/bedard/rainlabuserapi
        phpunit --coverage-clover clover.xml
